---
- name: Patch Management for Debian-based Systems
  hosts: my_servers
  become: yes
  gather_facts: yes
  tasks:
    - name: Ensure system is Debian-based
      assert:
        that: ansible_os_family == "Debian"
        fail_msg: "This playbook should only be run on Debian-based systems."

    - name: Update package cache
      apt:
        update_cache: yes

    - name: List available security updates
      shell: "apt list --upgradable 2>/dev/null | grep -i security || true"
      register: security_updates
      changed_when: false

    - name: Show available security updates
      debug:
        msg: "{{ security_updates.stdout_lines }}"
      when: security_updates.stdout_lines | length > 0

    - name: Fix interrupted dpkg if needed
      shell: dpkg --configure -a

    - name: Apply security updates
      apt:
        upgrade: dist
        only_upgrade: yes
        autoremove: yes

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot if required
      reboot:
        msg: "Rebooting to apply security updates"
        post_reboot_delay: 30
      when: reboot_required.stat.exists
